/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {
    ["Coated funky glass"]: THREE.MeshStandardMaterial;
  };
};

export default function TorusDan(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/media/torus_dan.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Coated funky glass"]}
        position={[0, 1.2, 0]}
        rotation={[0.6, 0.5, -0.2]}
        scale={1.2}
      />
    </group>
  );
}

useGLTF.preload("/media/torus_dan.glb");
