/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/media/torus_dan.glb --transform 
Files: public/media/torus_dan.glb [238.75KB] > /Users/danilonovais/hero-port/torus_dan-transformed.glb [28.64KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF("/Torus_dan");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Coated funky glass']} position={[-0.04, 1.233, 0.005]} rotation={[0.556, 0.534, -0.156]} scale={1.17} />
    </group>
  )
}

useGLTF.preload("/Torus_dan.glb");
